---
title: "data_scraping"
output: html_document
date: "2023-06-06"
---

113-04 Fall 2020 
```{r}
##install.packages("tcltk2")
##install.packages("PDE", dependencies = TRUE)

##install.packages("pdftools")
library(tidyverse)
library(pdftools)

## scan for hurtful and insensitive wording

evals_pdf <- pdf_text("STAT113_Fall_2020_1.pdf") 
evals_pdf 

## https://crimebythenumbers.com/scrape-table.html
tab <- pdf_text("STAT113_Fall_2020_1.pdf")
head(tab)
first_page <- strsplit(tab[1], "\n")[[1]]
first_page

first_page_zeroes <- str_replace_all(first_page,
                                     pattern = "-",
                                     replacement = "0")
first_page_zeroes

only_numbers <- str_extract_all(first_page_zeroes, "\\d+")
only_numbers

metadata_df <- tibble::tibble(control_num = only_numbers[[1]][2],
                              year = only_numbers[[2]][1],
                              course_num = only_numbers[[2]][3],
                              n_evals = only_numbers[[4]][1],
                              n_evals_univ = only_numbers[[8]][1])
metadata_df
```

question 1
```{r}
q1_indeces <- c(63, 64, 65, 66, 67, 68, 69)
q1 <- only_numbers[q1_indeces]
q1

q1[[1]] <- q1[[1]][1:3]
q1[[2]] <- q1[[2]][1:3]
q1[[3]] <- q1[[3]][1:3]
q1[[4]] <- q1[[4]][1:3]
q1[[5]] <- q1[[5]][1:3]
q1[[6]] <- q1[[6]][1:3]
q1

q1_df <- do.call(rbind.data.frame, q1)
names(q1_df) <- c("n_students", "perc", "univ_perc")
q1_df

responses <- c("Strongly Agree",
               "Agree", 
               "Agree Somewhat",
               "Neutral",
               "Disagree Somewhat",
               "Disagree",
               "Disagree Strongly")

year <- c(only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1])

core_df_1 <- tibble::tibble(responses = responses,
                            q1_df) |>
  mutate(question = "Q1")
core_df_1

core_df_1 <- tibble::tibble(year = year, 
                            core_df_1)
core_df_1
```

question 2
```{r}
q2_indeces <- c(7, 9, 10, 11, 12, 14, 16) ## back half of 16
q2 <- only_numbers[q2_indeces]
q2

# only getting last three numbers of 16 
q2[[7]] <- q2[[7]][4:6]
q2

q2_df <- do.call(rbind.data.frame, q2)
names(q2_df) <- c("n_students", "perc", "univ_perc")
q2_df

core_df_2 <- tibble::tibble(responses = responses,
                          q2_df) |>
  mutate(question = "Q2")
core_df_2

core_df_2 <- tibble::tibble(year = year,
                            core_df_2)
core_df_2 
```

question 3
```{r}
q3_indeces <- c(21, 23, 25, 26, 29, 31, 33)
q3 <- only_numbers[q3_indeces]
q3

q3[[1]] <- q3[[1]][4:6]
q3[[2]] <- q3[[2]][4:6]
q3[[4]] <- q3[[4]][4:6]
q3

q3_df <- do.call(rbind.data.frame, q3)
names(q3_df) <- c("n_students", "perc", "univ_perc")
q3_df

core_df_3 <- tibble::tibble(responses = responses,
                          q3_df) |>
  mutate(question = "Q3")
core_df_3

core_df_3 <- tibble::tibble(year = year,
                            core_df_3)
core_df_3
```

question 4a
```{r}
q4a_indeces <- c(38, 39, 40, 41, 43)
q4a <- only_numbers[q4a_indeces]
q4a

q4a[[1]] <- q4a[[1]][4:6]
q4a[[2]] <- q4a[[2]][4:6]
q4a[[3]] <- q4a[[3]][4:6]
q4a

q4a_df <- do.call(rbind.data.frame, q4a)
names(q4a_df) <- c("n_students", "perc", "univ_perc")
q4a_df

responses_2 <- c("Too High",
               "Somewhat High", 
               "Appropriate",
               "Somewhat Low",
               "Too Low") 

year_2 <- c(only_numbers[[2]][1],
            only_numbers[[2]][1],
            only_numbers[[2]][1],
            only_numbers[[2]][1],
            only_numbers[[2]][1])

core_df_4a <- tibble::tibble(responses = responses_2,
                          q4a_df) |>
  mutate(question = "Q4a")
core_df_4a

core_df_4a <- tibble::tibble(year_2 = year_2,
                            core_df_4a) 
core_df_4a <- core_df_4a |> rename(year = 'year_2')
core_df_4a
```

question 4b
```{r}
q4b_indeces <- c(50, 52, 54, 56, 57)
q4b <- only_numbers[q4b_indeces]
q4b

q4b_df <- do.call(rbind.data.frame, q4b)
names(q4b_df) <- c("n_students", "perc", "univ_perc")
q4b_df

core_df_4b <- tibble::tibble(responses = responses_2,
                          q4b_df) |>
  mutate(question = "Q4b")
core_df_4b

core_df_4b <- tibble::tibble(year_2 = year_2,
                            core_df_4b)
core_df_4b
core_df_4b <- core_df_4b |> rename(year = 'year_2')
core_df_4b
```

question 4c
```{r}
q4c_indeces <- c(63, 64, 65, 66, 67)
q4c <- only_numbers[q4c_indeces]
q4c

q4c[[1]] <- q4c[[1]][4:6]
q4c[[2]] <- q4c[[2]][4:6]
q4c[[3]] <- q4c[[3]][4:6]
q4c[[4]] <- q4c[[4]][4:6]
q4c[[5]] <- q4c[[5]][4:6]
q4c

q4c_df <- do.call(rbind.data.frame, q4c)
names(q4c_df) <- c("n_students", "perc", "univ_perc")
q4c_df

core_df_4c <- tibble::tibble(responses = responses_2,
                          q4c_df) |>
  mutate(question = "Q4c")
core_df_4c

core_df_4c <- tibble::tibble(year_2 = year_2,
                            core_df_4c)
core_df_4c

core_df_4c <- core_df_4c |> rename(year = 'year_2')
core_df_4c
```

```{r}
second_page <- strsplit(tab[2], "\n")[[1]]
second_page_zeroes <- str_replace_all(second_page,
                                     pattern = "-",
                                     replacement = "0")
second_page_zeroes
only_numbers_2 <- str_extract_all(second_page_zeroes, "\\d+")
only_numbers_2
```

question 5a
```{r}
q5a_indeces <- c(3, 4, 5, 6, 7, 8, 9)
q5a <- only_numbers_2[q5a_indeces]
q5a

q5a[[1]] <- q5a[[1]][1:3]
q5a[[2]] <- q5a[[2]][1:3]
q5a[[3]] <- q5a[[3]][1:3]
q5a[[4]] <- q5a[[4]][1:3]
q5a[[5]] <- q5a[[5]][1:3]
q5a[[6]] <- q5a[[6]][1:3]
q5a[[7]] <- q5a[[7]][1:3]
q5a

q5a_df <- do.call(rbind.data.frame, q5a)
names(q5a_df) <- c("n_students", "perc", "univ_perc")
q5a_df

core_df_5a <- tibble::tibble(responses = responses,
                          q5a_df) |>
  mutate(question = "Q5a")
core_df_5a

core_df_5a <- tibble::tibble(year = year,
                             core_df_5a) 
core_df_5a
```

question 5b
```{r}
q5b_indeces <- c(13, 14, 15, 16, 17, 18, 19)
q5b <- only_numbers_2[q5b_indeces]
q5b

q5b[[1]] <- q5b[[1]][1:3]
q5b[[2]] <- q5b[[2]][1:3]
q5b[[3]] <- q5b[[3]][1:3]
q5b[[4]] <- q5b[[4]][1:3]
q5b[[5]] <- q5b[[5]][1:3]
q5b[[6]] <- q5b[[6]][1:3]
q5b[[7]] <- q5b[[7]][1:3]
q5b

q5b_df <- do.call(rbind.data.frame, q5b)
names(q5b_df) <- c("n_students", "perc", "univ_perc")
q5b_df

core_df_5b <- tibble::tibble(responses = responses,
                          q5b_df) |>
  mutate(question = "Q5b")
core_df_5b

core_df_5b <- tibble::tibble(year = year,
                             core_df_5b)
core_df_5b
```

question 5c
```{r}
q5c_indeces <- c(24, 26, 27, 28, 31, 33, 34)
q5c <- only_numbers_2[q5c_indeces]
q5c

q5c[[2]] <- q5c[[2]][1:3]
q5c[[4]] <- q5c[[4]][1:3]
q5c[[7]] <- q5c[[7]][1:3]
q5c

q5c_df <- do.call(rbind.data.frame, q5c)
names(q5c_df) <- c("n_students", "perc", "univ_perc")
q5c_df

core_df_5c <- tibble::tibble(responses = responses,
                             q5c_df) |>
  mutate(question = "Q5c")
core_df_5c

core_df_5c <- tibble::tibble(year = year,
                             core_df_5c)
core_df_5c
```

question 6a
```{r}
q6a_indeces <- c(40, 41, 43, 45, 47, 48, 50)
q6a <- only_numbers_2[q6a_indeces]
q6a

q6a[[2]] <- q6a[[2]][1:3]
q6a[[7]] <- q6a[[7]][1:3]
q6a

q6a_df <- do.call(rbind.data.frame, q6a)
names(q6a_df) <- c("n_students", "perc", "univ_perc")
q6a_df

core_df_6a <- tibble::tibble(responses = responses,
                             q6a_df) |>
  mutate(question = "Q6a")
core_df_6a

core_df_6a <- tibble::tibble(year = year,
                             core_df_6a)
core_df_6a
```

question 6b
```{r}
q6b_indeces <- c(3, 4, 5, 6, 7, 8, 9)
q6b <- only_numbers_2[q6b_indeces]
q6b

q6b[[1]] <- q6b[[1]][4:6]
q6b[[2]] <- q6b[[2]][4:6]
q6b[[3]] <- q6b[[3]][4:6]
q6b[[4]] <- q6b[[4]][4:6]
q6b[[5]] <- q6b[[5]][4:6]
q6b[[6]] <- q6b[[6]][4:6]
q6b[[7]] <- q6b[[7]][4:6]
q6b

q6b_df <- do.call(rbind.data.frame, q6b)
names(q6b_df) <- c("n_students", "perc", "univ_perc")
q6b_df

core_df_6b <- tibble::tibble(responses = responses,
                             q6b_df) |>
  mutate(question = "Q6b")
core_df_6b

core_df_6b <- tibble::tibble(year = year, 
                             core_df_6b)
core_df_6b
```

question 6c
```{r}
q6c_indeces <- c(13, 14, 15, 16, 17, 18, 19)
q6c <- only_numbers_2[q6c_indeces]
q6c

q6c[[1]] <- q6c[[1]][4:6]
q6c[[2]] <- q6c[[2]][4:6]
q6c[[3]] <- q6c[[3]][4:6]
q6c[[4]] <- q6c[[4]][4:6]
q6c[[5]] <- q6c[[5]][4:6]
q6c[[6]] <- q6c[[6]][4:6]
q6c[[7]] <- q6c[[7]][4:6]
q6c

q6c_df <- do.call(rbind.data.frame, q6c)
names(q6c_df) <- c("n_students", "perc", "univ_perc")
q6c_df

core_df_6c <- tibble::tibble(responses = responses, 
                             q6c_df) |>
  mutate(question = "Q6c")
core_df_6c

core_df_6c <- tibble::tibble(year = year, 
                             core_df_6c) 
core_df_6c
```

primary reason for enrolling in course
```{r}
reasons_indeces <- c(16, 18, 19, 20, 21, 23, 26, 30)
reasons <- only_numbers[reasons_indeces] 
reasons

reasons[[1]] <- reasons[[1]][1:3]
reasons[[2]] <- reasons[[2]][1:3]
reasons[[3]] <- reasons[[3]][1:3]
reasons[[5]] <- reasons[[5]][1:3]
reasons[[6]] <- reasons[[6]][1:3]
reasons[[7]] <- reasons[[7]][1:3]
reasons

reasons_df <- do.call(rbind.data.frame, reasons)
names(reasons_df) <- c("n_students", "perc", "univ_perc")
reasons_df

reasons_responses <- c("Major",
                       "Minor",
                       "Distribution/Diversity",
                       "Interest in Subject",
                       "Instructor",
                       "Off Campus",
                       "Work on own Schedule",
                       "Other")

core_reasons_df <- tibble::tibble(responses = reasons_responses,
                                  reasons_df) |>
  mutate(question = "primary reason for enrollment")
core_reasons_df

year_3 <- c(only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1])

core_reasons_df <- tibble::tibble(year_3 = year_3,
                                  core_reasons_df)
core_reasons_df <- core_reasons_df |> rename(year = 'year_3')
core_reasons_df
```

gender 
```{r}
gender_indeces <- c(35, 37, 38, 39)
gender <- only_numbers[gender_indeces]
gender

gender[[3]] <- gender[[3]][1:3]
gender[[4]] <- gender[[4]][1:3]
gender

gender_df <- do.call(rbind.data.frame, gender)
names(gender_df) <- c("n_students", "perc", "univ_perc")
gender_df

gender_responses <- c("Male",
                      "Female",
                      "Other",
                      "Prefer not to disclose")

year_4 <- c(only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1])

core_gender_df <- tibble::tibble(responses = gender_responses,
                                 gender_df) |>
  mutate(question = "gender")
core_gender_df

core_gender_df <- tibble::tibble(year_4 = year_4,
                                 core_gender_df) 
core_gender_df <- core_gender_df |> rename(year = 'year_4')
core_gender_df
```

class year
```{r}
class_indeces <- c(44, 45, 47, 48, 51, 53)
class_year <- only_numbers[class_indeces]
class_year

class_year[[1]] <- class_year[[1]][1:3]
class_year[[2]] <- class_year[[2]][1:3]
class_year[[3]] <- class_year[[3]][1:3]
class_year

classyear_df <- do.call(rbind.data.frame, class_year)
names(classyear_df) <- c("n_students", "perc", "univ_perc")
classyear_df

class_responses <- c("First Year",
                     "Sophomore",
                     "Junior",
                     "Senior",
                     "Grad Student",
                     "Other")

year_5 <- c(only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1],
          only_numbers[[2]][1])

core_class_df <- tibble::tibble(responses = class_responses,
                                classyear_df) |>
  mutate(question = "class year")
core_class_df

core_class_df <- tibble::tibble(year_5 = year_5,
                                core_class_df)
core_class_df <- core_class_df |> rename(year = 'year_5')
core_class_df
```

summary of means 
```{r}
som_indeces <- c(22, 26, 28, 32, 34, 37, 39, 41, 44)
som <- only_numbers_2[som_indeces]
som

som[[1]] <- som[[1]][-1]
som[[2]] <- som[[2]][6:9]
som[[3]] <- som[[3]][6:9]
som[[4]] <- som[[4]][-1:-2]
som[[5]] <- som[[5]][6:9]
som[[6]] <- som[[6]][-1:-2]
som[[7]] <- som[[7]][-1:-2]
som[[8]] <- som[[8]][6:9]
som[[9]] <- som[[9]][-1:-2]
som

som_df <- do.call(rbind.data.frame, som)
names(som_df) <- c("mean", "x", "univ_mean", "y")
som_df

som_responses <- c("Valuable",
                   "Organized",
                   "Environmemt",
                   "Fair",
                   "Timely",
                   "Constructive",
                   "Recommend Prof",
                   "Recommend Course",
                   "Effective")

core_som_df <- tibble::tibble(responses = som_responses,
                              som_df) |>
  mutate(question = "summary of means")
core_som_df

core_som_df <- core_som_df |> unite("new_mean", c(mean, x),
                     sep = ".") |>
  unite("new_univ_mean", c(univ_mean, y),
        sep = ".") |>
  rename(mean = new_mean,
         univ_mean = new_univ_mean)
core_som_df
```

binding data sets to match csv
```{r}
questions_df <- bind_rows(core_df_1,
                          core_df_2,
                          core_df_3,
                          core_df_5a,
                          core_df_5b,
                          core_df_5c,
                          core_df_6a,
                          core_df_6b,
                          core_df_6c)
questions_df
```

binding all data sets, missing summary of means 
```{r}
full_df <- bind_rows(core_reasons_df,
                     core_gender_df, 
                     core_class_df, 
                     core_df_1, 
                     core_df_2, 
                     core_df_3, 
                     core_df_4a, 
                     core_df_4b, 
                     core_df_4c,
                     core_df_5a, 
                     core_df_5b, 
                     core_df_5c,
                     core_df_6a, 
                     core_df_6b, 
                     core_df_6c)
full_df 
```

```{r}
library(lubridate)
test <- questions_df |> mutate(year = as.numeric(year))
test
```

