---
title: "shiny_app"
output: html_document
date: "2023-06-13"
---

```{r}
library(tidyverse)
library(pdftools)
library(shiny)
source("pdf_function_full.R")
pdf_function_full("STAT113_Fall_2020_1.pdf")
source("meta_function.R")
meta_function("STAT113_Fall_2020_1.pdf")
source("sb_function.R")
sb_function("STAT113_Fall_2020_1.pdf")
```

most current version of shiny app
```{r}
ui <- fluidPage( 
  titlePanel("Upload File Here"),
  sidebarLayout(
    sidebarPanel(
      fileInput('file_input', 'Upload Student Evaluation
                File (.pdf format only)',
                accept = c('pdf')),
      radioButtons(inputId = "choose_graph", label = "Heatmap or Bar Plot",
                   choices = c("Heatmap", "Bar Plot")),
      radioButtons(inputId = "choose", label = "Counts or Percent of Students",
                   choices = c("Count", "Percent")),
      ),
    mainPanel(
      plotOutput("choose_plot", width = "100%"),
      tableOutput("pdfview"),
      tableOutput("pdf_display")
    ))
)
server <- function(input, output, session) {
  output$choose_plot <- renderPlot({
    req(input$file_input)
    if (input$choose_graph == "Heatmap") {
      pdf_df <- pdf_function_full(input$file_input$datapath)
    pdf_df <- pdf_df |> filter(responses_hm != "Too High" &
                        responses_hm != "Too Low" &
                        responses_hm != "Appropriate" &
                        responses_hm != "Somewhat High" &
                        responses_hm != "Somewhat Low")
    pdf_df <- pdf_df |> mutate(question_2 = 
                       fct_relevel(full_question, c("Q1. Valuable",
                                               "Q2. Organized",
                                               "Q3. Learning",
                                               "Q5a. Fair",
                                               "Q5b. Timely",
                                               "Q5c. Constructive",
                                               "Q6a. Rec_Prof",
                                               "Q6b. Rec_Course",
                                               "Q6c. Effective")))
    pdf_df <- pdf_df |> mutate(perc = as.double(perc))
    pdf_df <- pdf_df |> rename(Count = 'count_hm',
                               Percent = 'perc')
    meta_df <- meta_function(input$file_input$datapath)
    title <- paste(meta_df[1, 2], meta_df[1, 1], sep = " ", collapse = NULL)
    subtitle <- paste(meta_df[1, 3], meta_df[1, 4], sep = " ", collapse = NULL)
    ggplot(data = pdf_df, aes(x = responses_hm, y = fct_rev(question_2),
                                fill = .data[[input$choose]])) +
    geom_tile() +
    scale_fill_viridis_c(direction = 1) +
      labs(x = "Responses",
           y = "Questions",
           fill = input$choose,
           title = title,
           subtitle = subtitle) +
      geom_shadowtext(aes(label = .data[[input$choose]],
                  fontface = 'bold'), size = 6,
                colour = "gray",
            show.legend = FALSE) +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5,
                                  size = 18),
            plot.subtitle = element_text(hjust = 0.5),
            legend.box.background = element_rect(colour = "black"),
            axis.text = element_text(size = 14),
            axis.title = element_text(size = 16),
            legend.title = element_text(size = 13,
                                        hjust = 0.5),
            legend.text = element_text(size = 10,
                                       hjust = 0.5)) 
    } else{
      pdf_df <- pdf_function_full(input$file_input$datapath)
    pdf_df <- pdf_df |> filter(responses_hm != "Too High" &
                        responses_hm != "Too Low" &
                        responses_hm != "Appropriate" &
                        responses_hm != "Somewhat High" &
                        responses_hm != "Somewhat Low")
    pdf_df <- pdf_df |> mutate(question_2 = 
                       fct_relevel(full_question, c("Q1. Valuable",
                                               "Q2. Organized",
                                               "Q3. Learning",
                                               "Q5a. Fair",
                                               "Q5b. Timely",
                                               "Q5c. Constructive",
                                               "Q6a. Rec_Prof",
                                               "Q6b. Rec_Course",
                                               "Q6c. Effective")))
    pdf_df <- pdf_df |> mutate(perc = as.double(perc))
    pdf_df <- pdf_df |> rename(Count = 'count_hm',
                               Percent = 'perc')
    meta_df <- meta_function(input$file_input$datapath)
    title <- paste(meta_df[1, 2], meta_df[1, 1], sep = " ", collapse = NULL)
    subtitle <- paste(meta_df[1, 3], meta_df[1, 4], sep = " ", collapse = NULL)
    ggplot(data = pdf_df, aes(x = responses_hm, y = .data[[input$choose]])) +
      geom_col(aes(fill = .data[[input$choose]])) +
      facet_wrap(~question_2) +
      labs(x = "Responses",
           y = input$choose,
           title = title,
           subtitle = subtitle) +
      scale_fill_viridis_c() +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5,
                                  size = 18),
            plot.subtitle = element_text(hjust = 0.5),
            legend.box.background = element_rect(colour = "black"),
            axis.text.x = element_text(size = 5.5,
                                       face = "bold"),
            axis.text.y = element_text(size = 12),
            axis.title = element_text(size = 16),
            legend.title = element_text(size = 13,
                                        hjust = 0.5),
            legend.text = element_text(size = 10,
                                       hjust = 0.5),
            strip.text.x = element_text(size = 14)) 
    }
  }, height = 400, width = 920)
  output$pdfview <- renderTable({
    req(input$file_input)
    meta_df <- meta_function(input$file_input$datapath)
    meta_df <- meta_df |> rename(Course_Number = 'course_num',
                                 Subject = 'subject',
                                 Semester = 'semester',
                                 Year = 'year',
                                 Control_Number = 'control_num',
                                 Total_Evals = 'n_evals',
                                 Total_Evals_University = 'n_evals_univ')
    return(meta_df)
  }, align = 'c')
  output$pdf_display <- renderTable({
    req(input$file_input)
    pdf_df <- pdf_function_full(input$file_input$datapath)
    pdf_df <- pdf_df |> filter(responses_hm != "Too High" &
                        responses_hm != "Too Low" &
                        responses_hm != "Appropriate" &
                        responses_hm != "Somewhat High" &
                        responses_hm != "Somewhat Low")
    pdf_display <- pdf_df |>
      select(responses, n_students, perc, univ_perc, full_question) |>
      rename(Responses = 'responses',
             Count = 'n_students',
             Percent_of_Students = 'perc',
             University_Percent = 'univ_perc',
             Question = 'full_question')
    pdf_display <- pdf_display |> filter(Responses == "Strongly Agree" |
                                           Responses == "Agree")
    return(head(pdf_display))
  }, align = 'l')
}
shinyApp(ui, server)
```

