---
title: "ordinal_regression_examples"
output: html_document
date: "2023-07-11"
---

```{r}
library(tidyverse)
require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
# install.packages("Hmisc")
require(reshape2)
```

```{r}
# Just for this example (skip for your analyses)
set.seed(5)
dat <- data.frame(x = factor(sample(1:3, 100, replace=T),
                             levels = 1:3,
                             labels = c("High", "Med", "Low")))

# Code to imitate if you need to reorder a factor
# (modify as needed)

# Current level ordering
levels(dat$x)

# Reorder
dat <- dat %>% 
  mutate(x_new = factor(x,
                        levels = c("Low", "Med", "High")))

# Check derivation
table(dat$x, dat$x_new, exclude=NULL)

# Check new level ordering
levels(dat$x_new)

# exactly the same except variables are leveled from low to high

fit.olr <- MASS::polr(depression ~ PAQ650,
                      data = nhanes,
                      Hess= T)
summary(fit.olr)
```

```{r}
dat <- read.dta("https://stats.idre.ucla.edu/stat/data/ologit.dta")
head(dat)

## one at a time, table apply, pared, and public
lapply(dat[, c("apply", "pared", "public")], table)

## three way cross tabs (xtabs) and flatten the table
ftable(xtabs(~ public + apply + pared, data = dat))

summary(dat$gpa)
sd(dat$gpa)

ggplot(dat, aes(x = apply, y = gpa)) +
  geom_boxplot(size = .75) +
  geom_jitter(alpha = .5) +
  facet_grid(pared ~ public, margins = TRUE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

## fit ordered logit model and store results 'm'
m <- polr(apply ~ pared + public + gpa, data = dat, Hess=TRUE)

## view a summary of the model
summary(m)

## store table
(ctable <- coef(summary(m)))

## calculate and store p values
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

## combined table
(ctable <- cbind(ctable, "p value" = p))

(ci <- confint(m)) # default method gives profiled CIs
confint.default(m) # CIs assuming normality

## odds ratios
exp(coef(m))

## OR and CI
exp(cbind(OR = coef(m), ci))

# These coefficients are called proportional odds ratios and we would interpret these pretty much as we would odds ratios from a binary logistic regression.

sf <- function(y) {
  c('Y>=1' = qlogis(mean(y >= 1)),
    'Y>=2' = qlogis(mean(y >= 2)),
    'Y>=3' = qlogis(mean(y >= 3)))
}

# not working
(s <- with(dat, summary(as.numeric(apply) ~ pared + public + gpa, fun=sf)))

glm(I(as.numeric(apply) >= 2) ~ pared, family="binomial", data = dat)
glm(I(as.numeric(apply) >= 3) ~ pared, family="binomial", data = dat)

# not working 
s[, 4] <- s[, 4] - s[, 3]
s[, 3] <- s[, 3] - s[, 3]
s # print
plot(s, which=1:3, pch=1:3, xlab='logit', main=' ', xlim=range(s[,3:4]))

newdat <- data.frame(
  pared = rep(0:1, 200),
  public = rep(0:1, each = 200),
  gpa = rep(seq(from = 1.9, to = 4, length.out = 100), 4))

newdat <- cbind(newdat, predict(m, newdat, type = "probs"))

##show first few rows
head(newdat)

lnewdat <- melt(newdat, id.vars = c("pared", "public", "gpa"),
  variable.name = "Level", value.name="Probability")
## view first few rows
head(lnewdat)

ggplot(lnewdat, aes(x = gpa, y = Probability, colour = Level)) +
  geom_line() + facet_grid(pared ~ public, labeller="label_both")
```

```{r}
# install.packages("carData")
library(carData)
library(MASS)
data(WVS) 
head(WVS)

summary(WVS)

ggplot(WVS, aes(x = poverty, y = age, fill = poverty)) +   
  geom_boxplot(size = .75) +   
  facet_grid(country ~ gender, margins = FALSE) +   
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

model_fit <- polr(poverty~religion+degree+country+age+gender, data = WVS, Hess = TRUE)
summary(model_fit)

summary_table <- coef(summary(model_fit))
pval <- pnorm(abs(summary_table[, "t value"]),lower.tail = FALSE)* 2
summary_table <- cbind(summary_table, "p value" = round(pval,3))
summary_table

new_data <- data.frame("religion"= "yes","degree"="no","country"="Norway","age"=30,"gender"="male")
round(predict(model_fit,new_data,type = "p"), 3)
```


